### ISSUE TITLE
EPE-22	Misc stats updates. 

### ISSUE THREAD

**Issue by seagrinch** [ooiepe/epe_modules#133]
Task 1 - Stats don’t seem to be appearing on the Admin Stats page
Task 2 - The Admin Stats / Google Analytics page shows an error until you select a specific item.
Task 3 - The year option still doesn’t show in the Google Analytics admin page
Note from Joe: Combined this into one task for now since the original estimate covered all 3

**Comment by acyu** [comment]
this fix requires the installation of a drupal contrib module: https://www.drupal.org/project/statistics_counter

https://github.com/ooiepe/epe_modules/pull/160

**Comment by seagrinch** [comment]
* Are statistics counts included on the resource detail pages anywhere?  I see there's a view with this commit, but not sure if/where it's included.
* Does this module simply log all-time hits?  So no breakdown by month/year etc?
* Does this module support top hits pages?

**Comment by acyu** [comment]
- The statistics count will be include on detail page with EPE-23 (I implemented on EPE-28 branch instead)
- There is a total view that I'll add to it,
- technically this module doesn't support top hit pages, at least not from view.  but we can extract that info from db table directly

**Comment by seagrinch** [comment]
Looking good, except for a few places that list total hits twice on a page, as noted in other tickets.  Closing.
