### ISSUE TITLE
EPE-38	Vimeo links

### ISSUE THREAD

**Issue by seagrinch** [ooiepe/epe_modules#149]
YouTube links appear to upload fine but Vimeo links do not (perhaps an https/http issue?)

**Comment by acyu** [comment]
Was there something else about this task?  I vaguely remember there might be.  I treid this locally, and I am not having any issue.

**Comment by seagrinch** [comment]
I just tried this out, and it seems I am also able to add and view YouTube and Vimeo resources.  However, there are issues with them in the LLB.  On the Intro/Background pages, they show up as clickable thumbnails in the slideshow, which take you to their respective detail pages.  This is fine, as this is the same approach we use for CM and EV.  However, in the Exploration section, neither YouTube or Vimeo files show properly.  So I think we need to fix that.

**Comment by seagrinch** [comment]
I just checked CM.  When you try to add Multimedia resources from the Resource Browser, they don't show up in the left sidebar.  Video files do (though there appears to be some flashing issues in Chrome) so you can then drag them onto concepts, but multimedia files don't even show up.

**Comment by seagrinch** [comment]
LLB is working.  Were you able to look into CM?

**Comment by seagrinch** [comment]
I'm going to close this issue, as #151 deals with url-based videos in CM
